/**
 * Site-wide constants.
 *
 * `siteUrl` is the single source of truth for canonical URLs, Open Graph
 * tags, sitemap.xml, rss.xml and robots.txt. Change it here and everything
 * downstream follows. No trailing slash.
 */

// TODO(content): set the production domain before the first real deploy — see CONTENT-NEEDED.md
export const siteUrl = 'https://kole-swapnil.github.io'

/** Shown as `og:site_name` and in the RSS channel title. */
export const siteName = 'Swapnil Kole'

/** Default <title> for the home page. Keep under ~60 characters. */
export const siteTitle = 'Swapnil Kole — Senior Software Engineer'

/**
 * Default meta description and OG description for the home page.
 * Keep between 120 and 160 characters so it is not truncated in results.
 */
export const siteDescription =
  'Senior software engineer, 6+ years. I build production web platforms, cloud infrastructure and the blockchain layer when a project needs one. React, Node, AWS, Terraform, Solidity.'

/** Default share card. 1200×630. Generated by `npm run og`. */
export const defaultOgImage = '/og-image.png'

/** Absolute URL helper. Accepts a leading-slash path and returns an origin-qualified URL. */
export function absoluteUrl(path = '/'): string {
  return `${siteUrl}${path.startsWith('/') ? path : `/${path}`}`
}

/** Every prerendered static route, used by the sitemap generator. */
export const staticRoutes = ['/'] as const
